### ISSUE TITLE
Jest RTL tests

### ISSUE THREAD

**Issue by TahmidU** [TahmidU/mosaic#174]
# TODO

## Components
- [x] Atom/Button (https://github.com/TahmidU/mosaic/pull/177)
- [x] Atom/Card (https://github.com/TahmidU/mosaic/pull/178)
- [x] Atom/Checkbox (https://github.com/TahmidU/mosaic/pull/179)
- [x] Atom/DropdownList (https://github.com/TahmidU/mosaic/pull/180)
- [x] Atom/ExternalLink (https://github.com/TahmidU/mosaic/pull/181)
- [x] Atom/Input (https://github.com/TahmidU/mosaic/pull/182, https://github.com/TahmidU/mosaic/pull/184)
- [x] Atom/ProgressiveCircle (https://github.com/TahmidU/mosaic/pull/183)
- [x] Atom/SelectTitleList (https://github.com/TahmidU/mosaic/pull/185)
- [x] Molecules/CastCard (https://github.com/TahmidU/mosaic/pull/186)
- [x] Molecules/TypeFilter (https://github.com/TahmidU/mosaic/pull/187)
- [x] Molecules/Filter (https://github.com/TahmidU/mosaic/pull/190)
- [x] Molecules/HorizonalList (https://github.com/TahmidU/mosaic/pull/191, https://github.com/TahmidU/mosaic/pull/201)
- [x] Molecules/MediaCard (https://github.com/TahmidU/mosaic/pull/193)
- [x] Molecules/MovieCard (https://github.com/TahmidU/mosaic/pull/194)
- [x] Molecules/ReviewStat (Already tested)
- [x] Molecules/ScrollDownBtn (No point testing this)
- [x] Molecules/SearchCard (https://github.com/TahmidU/mosaic/pull/195)
- [x] Molecules/SlideButton (https://github.com/TahmidU/mosaic/pull/196)
- [x] Molecules/Socials (https://github.com/TahmidU/mosaic/pull/197)
- [x] Molecules/StarRating (https://github.com/TahmidU/mosaic/pull/198)
- [x] Molecules/SubList (No point testing it, it's just atom/SelectTitleList and atom/DropdownList)
- [x] Molecules/VideoModal (https://github.com/TahmidU/mosaic/pull/199)
- [x] Organisms/Carousel (https://github.com/TahmidU/mosaic/pull/200)
- [x] Organisms/CastList (No point testing this, it's basically testing HorizontalList again)
- [x] Organisms/DetailsCard (https://github.com/TahmidU/mosaic/pull/202)
- [x] Organisms/Footer (No point testing this)
- [x] Organisms/Layout (No point testing this)
- [x] Organisms/MediaList (No point testing this, it's basically testing HorizontalList again)
- [x] Organisms/MovieList (No point testing this, it's basically testing HorizontalList again)
- [x] Organisms/Navbar (No point testing this)
- [x] Organisms/SearchInput (https://github.com/TahmidU/mosaic/pull/204)

## Utils
- [x] MathUtils (https://github.com/TahmidU/mosaic/pull/209)
- [x] RoutingUtils (https://github.com/TahmidU/mosaic/pull/207)
- [x] TestUtils (https://github.com/TahmidU/mosaic/pull/210)
- [x] TextUtils (https://github.com/TahmidU/mosaic/pull/206)

**Comment by TahmidU** [comment]
All RTL tests complete
